version: "3.8"

network:
  my_net:
    name: my_net
    driver: bridge



services:
  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wp:/var/www/html/wordpress
    networks:
      - my_net
    depands_on : wordpress

  wordpress:
    build: requirement/wordpress/
    container_name: wordpress
    volumes:
      - wp:/var/www/html/wordpress
    networks:
      - my_net
      
      
      
  #mariadb:


volumes:

  wp: 
    name: wp
    dirver : local
    dirver_opts:
      type: none
      o : bind
      device : /home/jawaher/Documents/volumes/wordpress
